<?php

namespace Database\Seeders;

use App\Models\config\Almacen;
use App\Models\config\Modulo;
use App\Models\config\Sede;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        Modulo::withoutEvents(function () {
            DB::table('SYSMODULO')->insert([
                [
                    'MOD_CODIGO' => '001',
                    'MOD_NOMBRE' => 'CONFIGURACIONES',
                    'MOD_DETALL' => 'CONFIGURACIONES DEL SISTEMA',
                    'MOD_URL'    => '/configuracion',
                    'MOD_ICONO'  => 'fa-solid fa-gear',
                    'MOD_PARENT' => '/home',
                    'MOD_TIPO'  =>  '1',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '002',
                    'MOD_NOMBRE' => 'COMERCIAL',
                    'MOD_DETALL' => 'MODULO COMERCIAL',
                    'MOD_URL'    => '/comercial',
                    'MOD_ICONO'  => 'fa-solid fa-cash-register',
                    'MOD_PARENT' => '/home',
                    'MOD_TIPO'  =>  '1',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '003',
                    'MOD_NOMBRE' => 'SISTEMAS',
                    'MOD_DETALL' => 'MODULO SISTEMAS',
                    'MOD_URL'    => '/sistemas',
                    'MOD_ICONO'  => 'fa-solid fa-cash-register',
                    'MOD_PARENT' => '/home',
                    'MOD_TIPO'  =>  '1',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '004',
                    'MOD_NOMBRE' => 'CONTABILIDAD',
                    'MOD_DETALL' => 'MODULO CONTABILIDAD',
                    'MOD_URL'    => '/contabilidad',
                    'MOD_ICONO'  => 'fa-regular fa-credit-card',
                    'MOD_PARENT' => '/home',
                    'MOD_TIPO'  =>  '1',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '005',
                    'MOD_NOMBRE' => 'INVENTARIOS',
                    'MOD_DETALL' => 'MODULO INVENTARIOS',
                    'MOD_URL'    => '/inventarios',
                    'MOD_ICONO'  => 'fa-solid fa-truck-ramp-box',
                    'MOD_PARENT' => '/home',
                    'MOD_TIPO'   => '1',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '006',
                    'MOD_NOMBRE' => 'BITACORA',
                    'MOD_DETALL' => 'BITACORA DEL SISTEMA',
                    'MOD_URL'    => '/bitacora',
                    'MOD_ICONO'  => 'fa-solid fa-clock-rotate-left',
                    'MOD_PARENT' => '/home',
                    'MOD_TIPO'   => '1',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '007',
                    'MOD_NOMBRE' => 'ALMACENES',
                    'MOD_DETALL' => 'LISTA Y GESTIONAR ALMACENES',
                    'MOD_URL'    => '/almacenes',
                    'MOD_ICONO'  => 'fa-solid fa-warehouse',
                    'MOD_PARENT' => '/configuracion',
                    'MOD_TIPO'  =>  '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '008',
                    'MOD_NOMBRE' => 'SEDES',
                    'MOD_DETALL' => 'LISTA Y GESTIONAR SEDES',
                    'MOD_URL'    => '/sedes',
                    'MOD_ICONO'  => 'fa-solid fa-store',
                    'MOD_PARENT' => '/configuracion',
                    'MOD_TIPO'  =>  '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '009',
                    'MOD_NOMBRE' => 'AREAS',
                    'MOD_DETALL' => 'LISTA Y GESTIONAR AREAS',
                    'MOD_URL'    => '/areas',
                    'MOD_ICONO'  => 'fa-solid fa-stapler',
                    'MOD_PARENT' => '/configuracion',
                    'MOD_TIPO'  =>  '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '010',
                    'MOD_NOMBRE' => 'MODULOS',
                    'MOD_DETALL' => 'LISTA Y GESTIONAR MODULOS',
                    'MOD_URL'    => '/modulos',
                    'MOD_ICONO'  => 'fa-solid fa-server',
                    'MOD_PARENT' => '/configuracion',
                    'MOD_TIPO'  =>  '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '011',
                    'MOD_NOMBRE' => 'ROLES',
                    'MOD_DETALL' => 'LISTA Y GESTIONAR ROLES',
                    'MOD_URL'    => '/roles',
                    'MOD_ICONO'  => 'fa-solid fa-key',
                    'MOD_PARENT' => '/configuracion',
                    'MOD_TIPO'   =>  '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '012',
                    'MOD_NOMBRE' => 'USUARIOS',
                    'MOD_DETALL' => 'LISTA Y GESTIONAR USUARIOS',
                    'MOD_URL'    => '/usuarios',
                    'MOD_ICONO'  => 'fa-solid fa-users',
                    'MOD_PARENT' => '/configuracion',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '013',
                    'MOD_NOMBRE' => 'VENTAS GENERAL',
                    'MOD_DETALL' => 'INFORME VENTAS',
                    'MOD_URL'    => '/ventas',
                    'MOD_ICONO'  => 'fa-solid fa-cart-shopping',
                    'MOD_PARENT' => '/comercial',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '014',
                    'MOD_NOMBRE' => 'VENTAS SEDE',
                    'MOD_DETALL' => 'INFORME VENTAS POR SEDE',
                    'MOD_URL'    => '/venta-sede',
                    'MOD_ICONO'  => 'fa-solid fa-shop',
                    'MOD_PARENT' => '/comercial',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '015',
                    'MOD_NOMBRE' => 'VENTAS VENDEDOR',
                    'MOD_DETALL' => 'INFORME VENTAS POR VENDEDOR',
                    'MOD_URL'    => '/ventas-vendedor',
                    'MOD_ICONO'  => 'fa-solid fa-file-invoice-dollar',
                    'MOD_PARENT' => '/comercial',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '016',
                    'MOD_NOMBRE' => 'IMPORTAR VENTAS',
                    'MOD_DETALL' => 'IMPORTAR ARCHIVO DE VENTAS',
                    'MOD_URL'    => '/importar-ventas',
                    'MOD_ICONO'  => 'fa-solid fa-file-import',
                    'MOD_PARENT' => '/comercial',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '017',
                    'MOD_NOMBRE' => 'EQUIPOS',
                    'MOD_DETALL' => 'LISTADO DE EQUIPOS',
                    'MOD_URL'    => '/equipos',
                    'MOD_ICONO'  => 'fa-solid fa-toolbox',
                    'MOD_PARENT' => '/sistemas',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '018',
                    'MOD_NOMBRE' => 'MANTENIMIENTOS',
                    'MOD_DETALL' => 'LISTADO DE MANTENIMIENTOS',
                    'MOD_URL'    => '/mantenimientos',
                    'MOD_ICONO'  => 'fa-solid fa-wrench',
                    'MOD_PARENT' => '/sistemas',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '019',
                    'MOD_NOMBRE' => 'CONTRASEÑAS',
                    'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS',
                    'MOD_URL'    => '/contrasenas',
                    'MOD_ICONO'  => 'fa-solid fa-lock',
                    'MOD_PARENT' => '/sistemas',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '020',
                    'MOD_NOMBRE' => 'CARPETAS',
                    'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS CARPETAS',
                    'MOD_URL'    => '/clacarpetas',
                    'MOD_ICONO'  => 'fa-solid fa-folder',
                    'MOD_PARENT' => '/contrasenas',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '021',
                    'MOD_NOMBRE' => 'DISPOSITIVOS',
                    'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS EQUIPOS',
                    'MOD_URL'    => '/claequipos',
                    'MOD_ICONO'  => 'fa-solid fa-box',
                    'MOD_PARENT' => '/contrasenas',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '022',
                    'MOD_NOMBRE' => 'DOMINIOS',
                    'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS DOMINIOS',
                    'MOD_URL'    => '/cladominios',
                    'MOD_ICONO'  => 'fa-solid fa-globe',
                    'MOD_PARENT' => '/contrasenas',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '023',
                    'MOD_NOMBRE' => 'CORREOS',
                    'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS CORREOS',
                    'MOD_URL'    => '/clacorreo',
                    'MOD_ICONO'  => 'fa-solid fa-envelope',
                    'MOD_PARENT' => '/contrasenas',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '024',
                    'MOD_NOMBRE' => 'RESUMEN',
                    'MOD_DETALL' => 'RESUME INGRESOS',
                    'MOD_URL'    => '/resumen',
                    'MOD_ICONO'  => 'fa-solid fa-calculator',
                    'MOD_PARENT' => '/contabilidad',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '025',
                    'MOD_NOMBRE' => 'TARJETAS',
                    'MOD_DETALL' => 'REGISTRAR Y LISTA DE INGRESOS TARJETAS',
                    'MOD_URL'    => '/tarjetas',
                    'MOD_ICONO'  => 'fa-brands fa-cc-visa',
                    'MOD_PARENT' => '/contabilidad',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '026',
                    'MOD_NOMBRE' => 'CONCILIACION',
                    'MOD_DETALL' => 'REGISTRAR Y LISTA DE CONCILIACION',
                    'MOD_URL'    => '/conciliaciones',
                    'MOD_ICONO'  => 'fa-solid fa-money-bill-transfer',
                    'MOD_PARENT' => '/contabilidad',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '027',
                    'MOD_NOMBRE' => 'CUENTAS',
                    'MOD_DETALL' => 'CONSULTAR CUENTAS',
                    'MOD_URL'    => '/contabilidad/cuentas',
                    'MOD_ICONO'  => 'fa-regular fa-clipboard',
                    'MOD_PARENT' => '/contabilidad',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '028',
                    'MOD_NOMBRE' => 'REPORTES',
                    'MOD_DETALL' => 'CONSULTAR MOVIMIENTOS',
                    'MOD_URL'    => '/informe-contabilidad',
                    'MOD_ICONO'  => 'fa-regular fa-clipboard',
                    'MOD_PARENT' => '/contabilidad',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '029',
                    'MOD_NOMBRE' => 'FACTURAS',
                    'MOD_DETALL' => 'LISTAR Y REGISTRAR FACTURAS',
                    'MOD_URL'    => '/facturas',
                    'MOD_ICONO'  => 'fa-solid fa-receipt',
                    'MOD_PARENT' => '/inventarios',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '030',
                    'MOD_NOMBRE' => 'COMPRAS',
                    'MOD_DETALL' => 'INFORME DE COMPRAS',
                    'MOD_URL'    => '/compras',
                    'MOD_ICONO'  => 'fa-solid fa-file-invoice-dollar',
                    'MOD_PARENT' => '/inventarios',
                    'MOD_TIPO'   => '2',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '031',
                    'MOD_NOMBRE' => 'COMPRAS GENERALES',
                    'MOD_DETALL' => 'INFORME DE COMPRAS',
                    'MOD_URL'    => '/compra',
                    'MOD_ICONO'  => 'fa-solid fa-money-bill',
                    'MOD_PARENT' => '/compras',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '032',
                    'MOD_NOMBRE' => 'COMPRAS SEDES',
                    'MOD_DETALL' => 'INFORME DE COMPRAS POR SEDE',
                    'MOD_URL'    => '/compras-sede',
                    'MOD_ICONO'  => 'fa-solid fa-shop',
                    'MOD_PARENT' => '/compras',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '033',
                    'MOD_NOMBRE' => 'COMPRAS POR PROVEEDOR',
                    'MOD_DETALL' => 'INFORME DE COMPRAS POR PROVEEDORES',
                    'MOD_URL'    => '/compras-proveedor',
                    'MOD_ICONO'  => 'fa-solid fa-user-tie',
                    'MOD_PARENT' => '/compras',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'MOD_CODIGO' => '034',
                    'MOD_NOMBRE' => 'IMPORTAR COMPRAS',
                    'MOD_DETALL' => 'IMPORTAR ARCHIVO DE COMPRAS',
                    'MOD_URL'    => '/importar-compras',
                    'MOD_ICONO'  => 'fa-solid fa-file-import',
                    'MOD_PARENT' => '/compras',
                    'MOD_TIPO'   => '3',
                    'MOD_EQUIPO' => 'MT-SISTEMAS',
                    'MOD_CODOPE' => '1',
                    'MOD_CODUSU' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            ]);
        });

        Role::withoutEvents(function () {

        $admin = Role::create([
            'code' => '001',
            'name' => 'Administrador',
            'detail' => 'Rol Administrador',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $super = Role::create([
            'code' => '002',
            'name'   => 'Supervisor',
            'detail' => 'Rol Supervisor',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $user = Role::create([
            'code' => '003',
            'name'   => 'Usuario',
            'detail' => 'Rol Usuario',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //CONFIG
        $permiso1 = Permission::create([
            'code' => '001',
            'name' => 'configuracion.index',
            'detail' => 'Menu Configuracion',
            'codmod' => 'CONFIGURACIONES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //COMERCIAL
        $permiso2 = Permission::create([
            'code' => '002',
            'name' => 'comercial.index',
            'detail' => 'Menu Comercial',
            'codmod' => 'COMERCIAL',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //COMERCIAL
        $permiso3 = Permission::create([
            'code'   => '003',
            'name'   => 'sistemas.index',
            'detail' => 'Menu Sistemas',
            'codmod' => 'SISTEMAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //BITACORA
        $permiso4 = Permission::create([
            'code' => '004',
            'name' => 'historial.index',
            'detail' => 'Ver Movimientos del Sistema',
            'codmod' => 'BITACORA',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //ALMACENES
        $permiso5 = Permission::create([
            'code' => '005',
            'name' => 'almacenes.index',
            'detail' => 'Ver almacenes',
            'codmod' => 'ALMACENES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso6 = Permission::create([
            'code' => '006',
            'name' => 'almacenes.store',
            'detail' => 'Crear almacenes',
            'codmod' => 'ALMACENES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso7 = Permission::create([
            'code' => '007',
            'name' => 'almacenes.update',
            'detail' => 'Editar almacenes',
            'codmod' => 'ALMACENES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso8 = Permission::create([
            'code' => '008',
            'name' => 'almacenes.destroy',
            'detail' => 'Eliminar almacenes',
            'codmod' => 'ALMACENES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //SEDES
        $permiso9 = Permission::create([
            'code' => '009',
            'name' => 'sedes.index',
            'detail' => 'Ver sedes',
            'codmod' => 'SEDES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso10 = Permission::create([
            'code' => '010',
            'name' => 'sedes.store',
            'detail' => 'Crear sedes',
            'codmod' => 'SEDES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso11 = Permission::create([
            'code' => '011',
            'name' => 'sedes.update',
            'detail' => 'Editar sedes',
            'codmod' => 'SEDES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso12 = Permission::create([
            'code' => '012',
            'name' => 'sedes.destroy',
            'detail' => 'Eliminar sedes',
            'codmod' => 'SEDES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //AREAS
        $permiso13 = Permission::create([
            'code' => '013',
            'name' => 'areas.index',
            'detail' => 'Ver areas',
            'codmod' => 'AREAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso14 = Permission::create([
            'code' => '014',
            'name' => 'areas.store',
            'detail' => 'Crear areas',
            'codmod' => 'AREAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso15 = Permission::create([
            'code' => '015',
            'name' => 'areas.update',
            'detail' => 'Editar areas',
            'codmod' => 'AREAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso16 = Permission::create([
            'code' => '016',
            'name' => 'areas.destroy',
            'detail' => 'Eliminar areas',
            'codmod' => 'AREAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //MODULOS
        $permiso17 = Permission::create([
            'code' => '017',
            'name' => 'modulos.index',
            'detail' => 'Ver modulos',
            'codmod' => 'MODULOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso18 = Permission::create([
            'code' => '018',
            'name' => 'modulos.store',
            'detail' => 'Crear modulos',
            'codmod' => 'MODULOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso19 = Permission::create([
            'code' => '019',
            'name' => 'modulos.update',
            'detail' => 'Editar modulos',
            'codmod' => 'MODULOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso20 = Permission::create([
            'code' => '020',
            'name' => 'modulos.destroy',
            'detail' => 'Eliminar modulos',
            'codmod' => 'MODULOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //RolS
        $permiso21 = Permission::create([
            'code' => '021',
            'name' => 'Rols.index',
            'detail' => 'Ver Rols',
            'codmod' => 'ROLES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso22 = Permission::create([
            'code' => '022',
            'name' => 'Rols.store',
            'detail' => 'Crear Rols',
            'codmod' => 'ROLES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso23 = Permission::create([
            'code' => '023',
            'name' => 'Rols.update',
            'detail' => 'Editar Rols',
            'codmod' => 'ROLES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso24 = Permission::create([
            'code' => '024',
            'name' => 'Rols.destroy',
            'detail' => 'Eliminar Rols',
            'codmod' => 'ROLES',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //USUARIOS
        $permiso25 = Permission::create([
            'code' => '025',
            'name' => 'usuarios.index',
            'detail' => 'Ver usuarios',
            'codmod' => 'USUARIOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso26 = Permission::create([
            'code'   => '026',
            'name'   => 'usuarios.store',
            'detail' => 'Crear usuarios',
            'codmod' => 'USUARIOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso27 = Permission::create([
            'code' => '027',
            'name' => 'usuarios.update',
            'detail' => 'Editar usuarios',
            'codmod' => 'USUARIOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso28 = Permission::create([
            'code' => '028',
            'name' => 'usuarios.destroy',
            'detail' => 'Eliminar usuarios',
            'codmod' => 'USUARIOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso29 = Permission::create([
            'code'   => '029',
            'name'   => 'vengeneral.index',
            'detail' => 'Ver Ventas Generales',
            'codmod' => 'COMERCIAL',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso30 = Permission::create([
            'code'   => '030',
            'name'   => 'vensede.index',
            'detail' => 'Ver Ventas Sedes',
            'codmod' => 'COMERCIAL',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso31 = Permission::create([
            'code'   => '031',
            'name'   => 'venvendedor.index',
            'detail' => 'Ver Ventas Vendedor',
            'codmod' => 'COMERCIAL',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso31 = Permission::create([
            'code'   => '032',
            'name'   => 'venimportar.index',
            'detail' => 'Impomtar Archivo Ventas',
            'codmod' => 'COMERCIAL',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //EQUIPOS
        $permiso32 = Permission::create([
            'code' => '033',
            'name' => 'equipos.index',
            'detail' => 'Ver Equipos',
            'codmod' => 'EQUIPOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso33 = Permission::create([
            'code'   => '034',
            'name'   => 'equipos.store',
            'detail' => 'Crear Equipo',
            'codmod' => 'EQUIPOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso34 = Permission::create([
            'code' => '035',
            'name' => 'equipos.update',
            'detail' => 'Editar Equipo',
            'codmod' => 'EQUIPOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso35 = Permission::create([
            'code' => '036',
            'name' => 'equipos.destroy',
            'detail' => 'Eliminar Equipo',
            'codmod' => 'EQUIPOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //MANTENIMIENTOS
        $permiso36 = Permission::create([
            'code' => '037',
            'name' => 'mantenimientos.index',
            'detail' => 'Ver Mantenimientos',
            'codmod' => 'MANTENIMIENTOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso37 = Permission::create([
            'code'   => '038',
            'name'   => 'mantenimientos.store',
            'detail' => 'Crear Mantenimiento',
            'codmod' => 'MANTENIMIENTOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso38 = Permission::create([
            'code' => '039',
            'name' => 'mantenimientos.update',
            'detail' => 'Editar Mantenimiento',
            'codmod' => 'MANTENIMIENTOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso39 = Permission::create([
            'code' => '040',
            'name' => 'mantenimientos.destroy',
            'detail' => 'Eliminar Mantenimientos',
            'codmod' => 'MANTENIMIENTOS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //CARPETAS
        $permiso40 = Permission::create([
            'code' => '041',
            'name' => 'clacarpetas.index',
            'detail' => 'Ver Contraseñas Carpetas',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso41 = Permission::create([
            'code'   => '042',
            'name'   => 'clacarpetas.store',
            'detail' => 'Crear Contraseñas Carpetas',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso42 = Permission::create([
            'code' => '043',
            'name' => 'clacarpetas.update',
            'detail' => 'Editar Contraseñas Carpetas',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso43 = Permission::create([
            'code' => '044',
            'name' => 'clacarpetas.destroy',
            'detail' => 'Eliminar Contraseñas Carpetas',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //EQUIPOS
        $permiso44 = Permission::create([
            'code' => '045',
            'name' => 'claequipos.index',
            'detail' => 'Ver Contraseñas Equipos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso45 = Permission::create([
            'code'   => '046',
            'name'   => 'claequipos.store',
            'detail' => 'Crear Contraseñas Equipos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso46 = Permission::create([
            'code' => '047',
            'name' => 'claequipos.update',
            'detail' => 'Editar Contraseñas Equipos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso47 = Permission::create([
            'code' => '048',
            'name' => 'claequipos.destroy',
            'detail' => 'Eliminar Contraseñas Equipos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //DOMINIOS
        $permiso48 = Permission::create([
            'code' => '049',
            'name' => 'cladominios.index',
            'detail' => 'Ver Contraseñas Dominios',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso49 = Permission::create([
            'code'   => '050',
            'name'   => 'cladominios.store',
            'detail' => 'Crear Contraseñas Dominios',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso50 = Permission::create([
            'code' => '051',
            'name' => 'cladominios.update',
            'detail' => 'Editar Contraseñas Dominios',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso51 = Permission::create([
            'code' => '052',
            'name' => 'cladominios.destroy',
            'detail' => 'Eliminar Contraseñas Dominios',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        //CORREOS
        $permiso52 = Permission::create([
            'code' => '053',
            'name' => 'clacorreo.index',
            'detail' => 'Ver Contraseñas Correos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso53 = Permission::create([
            'code'   => '054',
            'name'   => 'clacorreo.store',
            'detail' => 'Crear Contraseñas Correos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso54 = Permission::create([
            'code' => '055',
            'name' => 'clacorreo.update',
            'detail' => 'Editar Contraseñas Correos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $permiso55 = Permission::create([
            'code' => '056',
            'name' => 'clacorreo.destroy',
            'detail' => 'Eliminar Contraseñas Correos',
            'codmod' => 'CONTRASEÑAS',
            'codope' => '1',
            'codusu' => '1',
            'equipe' => 'MT-SISTEMAS',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        User::withoutEvents(function () {
            User::factory()->create([
                'code'    => 'ADMIN',
                'name'      => 'Administrador',
                'email'     => 'administrador@example.com',
                'password'  => Hash::make('Admin123'),
                'codope'    => '1',
                'codusu'    => '1',
                'codalm'    => '1',
                'host'    => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            User::factory()->create([
                'code'    => 'APP',
                'name'    => 'Usuario de Aplicación',
                'email'   => 'usuario@app.com',
                'password' => Hash::make('App123'),
                'codope'  => '1',
                'codusu'  => '1',
                'codalm'  => '1',
                'host'    => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        $useradmin = User::find(1);
        $useradmin->roles()->attach(1);
        $admin->permissions()->attach([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56]);

        $userapp = User::find(2);
        $userapp->roles()->attach(3);
        $userapp->permissions()->attach([2]);
    });

        Almacen::withoutEvents(function() {
            DB::table('SYSALMACE')->insert([
                'ALM_CODIGO' => '0001',
                'ALM_NOMBRE' => 'INVERSIONES VADIHER S.A.S.',
                'ALM_DETALL' => 'GRUPO VADIHER',
                'ALM_NIT'    => '900705500-2',
                'ALM_EQUIPO' => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        Sede::withoutEvents(function() {
            DB::table('SYSSEDES')->insert([
                'SED_CODIGO' => '0001',
                'SED_NOMBRE' => 'MATERIALES METROPOLIS LA 19',
                'SED_DETALL' => 'SEDE LA 19',
                'SED_NIT'    => '900705500-2',
                'SED_TELEFO' => '3220000000',
                'SED_EMAIL' => 'inversionesvadiher@gmail.com',
                'SED_DIRECC' => 'Cra 19 N° 29S - 12C5',
                'SED_CODZON' => '4',
                'SED_CODSUB' => '47001',
                'SED_CODALM' => '1',
                'SED_EQUIPO' => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        DB::table('MOVCONFIG')->insert([
            [
                'MOV_CONMOV' => '000000001',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el modulo CONFIGURACIONES',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000002',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el modulo COMERCIAL',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000003',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el modulo SISTEMAS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000004',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el modulo BITACORA',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000005',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo ALMACENES',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000006',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo SEDES',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000007',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo AREAS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000008',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo MODULOS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000009',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo ROLES',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000010',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo USUARIOS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000011',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo VENTAS GENERAL',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000012',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo VENTAS SEDE',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000013',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo VENTAS VENDEDOR',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000014',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo IMPORTAR VENTAS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000015',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo EQUIPOS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000016',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el submodulo MANTENIMIENTOS',
                'MOV_CODMOD' => 'USUARIOS',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000017',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado el submodulo CONTRASEÑAS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000018',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado el items CARPETAS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000019',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el items EQUIPOS',
                'MOV_CODMOD' => 'USUARIOS',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000020',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el items DOMINIOS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000021',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el items CORREOS',
                'MOV_CODMOD' => 'CONFIGURACIONES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000022',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el rol Administrador',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000023',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el rol Supervisor',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000024',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el rol Usuario',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000025',
                'MOV_EVENTO' => 'Modificacion Perfil',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado el rol Administrador asl Usuario Admin',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000026',
                'MOV_EVENTO' => 'Modificacion Perfil',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado el rol Usuario al Usuario APP',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000027',
                'MOV_EVENTO' => 'Modificacion Perfil Seguridad',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado permisos al rol Administrador',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000028',
                'MOV_EVENTO' => 'Modificacion Perfil Seguridad',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado permisos al rol Usuario',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000029',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el Almacen INVERSIONES VADIGER S.A.S',
                'MOV_CODMOD' => 'ALMACENES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000030',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado la Sede MATERIALES METROPOLIS LA 19',
                'MOV_CODMOD' => 'SEDES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
