<?php

namespace Database\Seeders;

use App\Models\config\Almacen;
use App\Models\config\Modulo;
use App\Models\config\Sede;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::withoutEvents(function () {
            User::factory()->create([
                'code'    => 'ADMIN',
                'name'      => 'Administrador',
                'email'     => 'administrador@example.com',
                'password'  => Hash::make('Admin123'),
                'codope'    => '1',
                'codusu'    => '1',
                'codalm'    => '1',
                'host'    => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            User::factory()->create([
                'code'    => 'APP',
                'name'    => 'Usuario de Aplicación',
                'email'   => 'usuario@app.com',
                'password' => Hash::make('App123'),
                'codope'  => '1',
                'codusu'  => '1',
                'codalm'  => '1',
                'host'    => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        $modulos = [
            [
                'MOD_CODIGO' => '001',
                'MOD_NOMBRE' => 'CONFIGURACIONES',
                'MOD_DETALL' => 'CONFIGURACIONES DEL SISTEMA',
                'MOD_URL'    => '/configuracion',
                'MOD_ICONO'  => 'fa-solid fa-gear',
                'MOD_PARENT' => '/home',
                'MOD_TIPO'  =>  '1',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '002',
                'MOD_NOMBRE' => 'COMERCIAL',
                'MOD_DETALL' => 'MODULO COMERCIAL',
                'MOD_URL'    => '/comercial',
                'MOD_ICONO'  => 'fa-solid fa-cash-register',
                'MOD_PARENT' => '/home',
                'MOD_TIPO'  =>  '1',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '003',
                'MOD_NOMBRE' => 'SISTEMAS',
                'MOD_DETALL' => 'MODULO SISTEMAS',
                'MOD_URL'    => '/sistemas',
                'MOD_ICONO'  => 'fa-solid fa-cash-register',
                'MOD_PARENT' => '/home',
                'MOD_TIPO'  =>  '1',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '004',
                'MOD_NOMBRE' => 'CONTABILIDAD',
                'MOD_DETALL' => 'MODULO CONTABILIDAD',
                'MOD_URL'    => '/contabilidad',
                'MOD_ICONO'  => 'fa-regular fa-credit-card',
                'MOD_PARENT' => '/home',
                'MOD_TIPO'  =>  '1',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '005',
                'MOD_NOMBRE' => 'INVENTARIOS',
                'MOD_DETALL' => 'MODULO INVENTARIOS',
                'MOD_URL'    => '/inventarios',
                'MOD_ICONO'  => 'fa-solid fa-truck-ramp-box',
                'MOD_PARENT' => '/home',
                'MOD_TIPO'   => '1',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '006',
                'MOD_NOMBRE' => 'BITACORA',
                'MOD_DETALL' => 'BITACORA DEL SISTEMA',
                'MOD_URL'    => '/bitacora',
                'MOD_ICONO'  => 'fa-solid fa-clock-rotate-left',
                'MOD_PARENT' => '/home',
                'MOD_TIPO'   => '1',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '007',
                'MOD_NOMBRE' => 'ALMACENES',
                'MOD_DETALL' => 'LISTA Y GESTIONAR ALMACENES',
                'MOD_URL'    => '/almacenes',
                'MOD_ICONO'  => 'fa-solid fa-warehouse',
                'MOD_PARENT' => '/configuracion',
                'MOD_TIPO'  =>  '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '008',
                'MOD_NOMBRE' => 'SEDES',
                'MOD_DETALL' => 'LISTA Y GESTIONAR SEDES',
                'MOD_URL'    => '/sedes',
                'MOD_ICONO'  => 'fa-solid fa-store',
                'MOD_PARENT' => '/configuracion',
                'MOD_TIPO'  =>  '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '009',
                'MOD_NOMBRE' => 'AREAS',
                'MOD_DETALL' => 'LISTA Y GESTIONAR AREAS',
                'MOD_URL'    => '/areas',
                'MOD_ICONO'  => 'fa-solid fa-stapler',
                'MOD_PARENT' => '/configuracion',
                'MOD_TIPO'  =>  '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '010',
                'MOD_NOMBRE' => 'MODULOS',
                'MOD_DETALL' => 'LISTA Y GESTIONAR MODULOS',
                'MOD_URL'    => '/modulos',
                'MOD_ICONO'  => 'fa-solid fa-server',
                'MOD_PARENT' => '/configuracion',
                'MOD_TIPO'  =>  '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '011',
                'MOD_NOMBRE' => 'ROLES',
                'MOD_DETALL' => 'LISTA Y GESTIONAR ROLES',
                'MOD_URL'    => '/roles',
                'MOD_ICONO'  => 'fa-solid fa-key',
                'MOD_PARENT' => '/configuracion',
                'MOD_TIPO'   =>  '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '012',
                'MOD_NOMBRE' => 'USUARIOS',
                'MOD_DETALL' => 'LISTA Y GESTIONAR USUARIOS',
                'MOD_URL'    => '/usuarios',
                'MOD_ICONO'  => 'fa-solid fa-users',
                'MOD_PARENT' => '/configuracion',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '013',
                'MOD_NOMBRE' => 'VENTAS GENERAL',
                'MOD_DETALL' => 'INFORME VENTAS',
                'MOD_URL'    => '/ventas',
                'MOD_ICONO'  => 'fa-solid fa-cart-shopping',
                'MOD_PARENT' => '/comercial',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '014',
                'MOD_NOMBRE' => 'VENTAS SEDE',
                'MOD_DETALL' => 'INFORME VENTAS POR SEDE',
                'MOD_URL'    => '/venta-sede',
                'MOD_ICONO'  => 'fa-solid fa-shop',
                'MOD_PARENT' => '/comercial',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '015',
                'MOD_NOMBRE' => 'VENTAS VENDEDOR',
                'MOD_DETALL' => 'INFORME VENTAS POR VENDEDOR',
                'MOD_URL'    => '/ventas-vendedor',
                'MOD_ICONO'  => 'fa-solid fa-file-invoice-dollar',
                'MOD_PARENT' => '/comercial',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '016',
                'MOD_NOMBRE' => 'IMPORTAR VENTAS',
                'MOD_DETALL' => 'IMPORTAR ARCHIVO DE VENTAS',
                'MOD_URL'    => '/importar-ventas',
                'MOD_ICONO'  => 'fa-solid fa-file-import',
                'MOD_PARENT' => '/comercial',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '017',
                'MOD_NOMBRE' => 'EQUIPOS',
                'MOD_DETALL' => 'LISTADO DE EQUIPOS',
                'MOD_URL'    => '/equipos',
                'MOD_ICONO'  => 'fa-solid fa-toolbox',
                'MOD_PARENT' => '/sistemas',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '018',
                'MOD_NOMBRE' => 'MANTENIMIENTOS',
                'MOD_DETALL' => 'LISTADO DE MANTENIMIENTOS',
                'MOD_URL'    => '/mantenimientos',
                'MOD_ICONO'  => 'fa-solid fa-wrench',
                'MOD_PARENT' => '/sistemas',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '019',
                'MOD_NOMBRE' => 'CONTRASEÑAS',
                'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS',
                'MOD_URL'    => '/contrasenas',
                'MOD_ICONO'  => 'fa-solid fa-lock',
                'MOD_PARENT' => '/sistemas',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '020',
                'MOD_NOMBRE' => 'CARPETAS',
                'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS CARPETAS',
                'MOD_URL'    => '/clacarpetas',
                'MOD_ICONO'  => 'fa-solid fa-folder',
                'MOD_PARENT' => '/contrasenas',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '021',
                'MOD_NOMBRE' => 'DISPOSITIVOS',
                'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS EQUIPOS',
                'MOD_URL'    => '/claequipos',
                'MOD_ICONO'  => 'fa-solid fa-box',
                'MOD_PARENT' => '/contrasenas',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '022',
                'MOD_NOMBRE' => 'DOMINIOS',
                'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS DOMINIOS',
                'MOD_URL'    => '/cladominios',
                'MOD_ICONO'  => 'fa-solid fa-globe',
                'MOD_PARENT' => '/contrasenas',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '023',
                'MOD_NOMBRE' => 'CORREOS',
                'MOD_DETALL' => 'LISTADO DE CONTRASEÑAS CORREOS',
                'MOD_URL'    => '/clacorreo',
                'MOD_ICONO'  => 'fa-solid fa-envelope',
                'MOD_PARENT' => '/contrasenas',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '024',
                'MOD_NOMBRE' => 'RESUMEN',
                'MOD_DETALL' => 'RESUME INGRESOS',
                'MOD_URL'    => '/resumen',
                'MOD_ICONO'  => 'fa-solid fa-calculator',
                'MOD_PARENT' => '/contabilidad',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '025',
                'MOD_NOMBRE' => 'TARJETAS',
                'MOD_DETALL' => 'REGISTRAR Y LISTA DE INGRESOS TARJETAS',
                'MOD_URL'    => '/tarjetas',
                'MOD_ICONO'  => 'fa-brands fa-cc-visa',
                'MOD_PARENT' => '/contabilidad',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '026',
                'MOD_NOMBRE' => 'CONCILIACION',
                'MOD_DETALL' => 'REGISTRAR Y LISTA DE CONCILIACION',
                'MOD_URL'    => '/conciliaciones',
                'MOD_ICONO'  => 'fa-solid fa-money-bill-transfer',
                'MOD_PARENT' => '/contabilidad',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '027',
                'MOD_NOMBRE' => 'CUENTAS',
                'MOD_DETALL' => 'CONSULTAR CUENTAS',
                'MOD_URL'    => '/contabilidad/cuentas',
                'MOD_ICONO'  => 'fa-regular fa-clipboard',
                'MOD_PARENT' => '/contabilidad',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '028',
                'MOD_NOMBRE' => 'REPORTES',
                'MOD_DETALL' => 'CONSULTAR MOVIMIENTOS',
                'MOD_URL'    => '/informe-contabilidad',
                'MOD_ICONO'  => 'fa-regular fa-clipboard',
                'MOD_PARENT' => '/contabilidad',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '029',
                'MOD_NOMBRE' => 'FACTURAS',
                'MOD_DETALL' => 'LISTAR Y REGISTRAR FACTURAS',
                'MOD_URL'    => '/facturas',
                'MOD_ICONO'  => 'fa-solid fa-receipt',
                'MOD_PARENT' => '/inventarios',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '030',
                'MOD_NOMBRE' => 'COMPRAS',
                'MOD_DETALL' => 'INFORME DE COMPRAS',
                'MOD_URL'    => '/compras',
                'MOD_ICONO'  => 'fa-solid fa-file-invoice-dollar',
                'MOD_PARENT' => '/inventarios',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '031',
                'MOD_NOMBRE' => 'STOCK',
                'MOD_DETALL' => 'REFERENCIAS TRONCAL',
                'MOD_URL'    => '/inventarios/stock',
                'MOD_ICONO'  => 'fa-solid fa-truck-ramp-box',
                'MOD_PARENT' => '/inventarios',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '032',
                'MOD_NOMBRE' => 'TICKET',
                'MOD_DETALL' => 'GENERAR TICKETS',
                'MOD_URL'    => '/inventarios/ticket',
                'MOD_ICONO'  => 'fa-solid fa-truck-ramp-box',
                'MOD_PARENT' => '/inventarios',
                'MOD_TIPO'   => '2',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '1',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '033',
                'MOD_NOMBRE' => 'COMPRAS GENERALES',
                'MOD_DETALL' => 'INFORME DE COMPRAS',
                'MOD_URL'    => '/compra',
                'MOD_ICONO'  => 'fa-solid fa-money-bill',
                'MOD_PARENT' => '/compras',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '034',
                'MOD_NOMBRE' => 'COMPRAS SEDES',
                'MOD_DETALL' => 'INFORME DE COMPRAS POR SEDE',
                'MOD_URL'    => '/compras-sede',
                'MOD_ICONO'  => 'fa-solid fa-shop',
                'MOD_PARENT' => '/compras',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '035',
                'MOD_NOMBRE' => 'COMPRAS POR PROVEEDOR',
                'MOD_DETALL' => 'INFORME DE COMPRAS POR PROVEEDORES',
                'MOD_URL'    => '/compras-proveedor',
                'MOD_ICONO'  => 'fa-solid fa-user-tie',
                'MOD_PARENT' => '/compras',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOD_CODIGO' => '036',
                'MOD_NOMBRE' => 'IMPORTAR COMPRAS',
                'MOD_DETALL' => 'IMPORTAR ARCHIVO DE COMPRAS',
                'MOD_URL'    => '/importar-compras',
                'MOD_ICONO'  => 'fa-solid fa-file-import',
                'MOD_PARENT' => '/compras',
                'MOD_TIPO'   => '3',
                'MOD_EQUIPO' => 'MT-SISTEMAS',
                'MOD_ESTADO' => '0',
                'MOD_CODOPE' => '1',
                'MOD_CODUSU' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        foreach ($modulos as $modulo) {
            $newmodulo = Modulo::create($modulo);
        }

            $admin = Role::create([
                'code' => '001',
                'name' => 'Administrador',
                'detail' => 'Rol Administrador',
                'codope' => '1',
                'codusu' => '1',
                'equipe' => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $super = Role::create([
                'code' => '002',
                'name'   => 'Supervisor',
                'detail' => 'Rol Supervisor',
                'codope' => '1',
                'codusu' => '1',
                'equipe' => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $user = Role::create([
                'code' => '003',
                'name'   => 'Usuario',
                'detail' => 'Rol Usuario',
                'codope' => '1',
                'codusu' => '1',
                'equipe' => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        //CONFIG
        Almacen::withoutEvents(function() {
            DB::table('SYSALMACE')->insert([
                'ALM_CODIGO' => '0001',
                'ALM_NOMBRE' => 'INVERSIONES VADIHER S.A.S.',
                'ALM_DETALL' => 'GRUPO VADIHER',
                'ALM_NIT'    => '900705500-2',
                'ALM_EQUIPO' => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        Sede::withoutEvents(function() {
            DB::table('SYSSEDES')->insert([
                'SED_CODIGO' => '0001',
                'SED_NOMBRE' => 'MATERIALES METROPOLIS LA 19',
                'SED_DETALL' => 'SEDE LA 19',
                'SED_NIT'    => '900705500-2',
                'SED_TELEFO' => '3220000000',
                'SED_EMAIL' => 'inversionesvadiher@gmail.com',
                'SED_DIRECC' => 'Cra 19 N° 29S - 12C5',
                'SED_CODZON' => '4',
                'SED_CODSUB' => '47001',
                'SED_CODALM' => '1',
                'SED_EQUIPO' => 'MT-SISTEMAS',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        DB::table('MOVCONFIG')->insert([
            [
                'MOV_CONMOV' => '000000040',
                'MOV_EVENTO' => 'Modificacion Perfil',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado el rol Administrador asl Usuario Admin',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000041',
                'MOV_EVENTO' => 'Modificacion Perfil',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado el rol Usuario al Usuario APP',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000042',
                'MOV_EVENTO' => 'Modificacion Perfil Seguridad',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado permisos al rol Administrador',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000043',
                'MOV_EVENTO' => 'Modificacion Perfil Seguridad',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Asignado permisos al rol Usuario',
                'MOV_CODMOD' => 'ROLES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000044',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado el Almacen INVERSIONES VADIGER S.A.S',
                'MOV_CODMOD' => 'ALMACENES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'MOV_CONMOV' => '000000045',
                'MOV_EVENTO' => 'Adicion Registro',
                'MOV_CODOPE' => '1',
                'MOV_CODALM' => '1',
                'MOV_DETALL' => 'Se ha Adicionado la Sede MATERIALES METROPOLIS LA 19',
                'MOV_CODMOD' => 'SEDES',
                'MOV_EQUIPO' => 'MT-SISTEMAS',
                'MOV_PERIOD' => '2025',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}

